# Generated by Django 4.2.23 on 2025-07-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='assets/images/avatars/avatar-1.jpg', upload_to='media/assets/images/avatars/'),
        ),
    ]
