# Generated by Django 4.2.23 on 2025-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(choices=[('none', 'None'), ('single', 'Single'), ('in_a_rel', 'In a relationship'), ('merried', 'Merried'), ('engaged', 'Engaged')], default='none', max_length=50),
        ),
    ]
