# Generated by Django 4.2.23 on 2025-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='assets/images/avatars/avatar-1.jpg', upload_to='assets/images/avatars/'),
        ),
    ]
