# Generated by Django 4.2.23 on 2025-07-27 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 14, 59, 24, 591863)),
        ),
    ]
