# Generated by Django 4.2.23 on 2025-07-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('pic', models.ImageField(default='media/assets/images/avatars/avatar-1.jpg', upload_to='media/assets/images/avatars/')),
                ('locations', models.CharField(blank=True, max_length=150, null=True)),
                ('working_at', models.CharField(blank=True, max_length=55, null=True)),
                ('relationship', models.CharField(choices=[('none', 'None'), ('single', 'Single'), ('in_a_rel', 'In a relationship'), ('merried', 'merried'), ('engaged', 'Engaged')], default='none', max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('show_activity', models.BooleanField(default=True)),
                ('allow_comms', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
